### ISSUE TITLE
Please consider republishing to npm

### ISSUE THREAD

**Issue by newtang** [peterbraden/ical.js#96]
After hours of fiddling, I realized that the published version of ical.js is very out of date on npm. Support for the `recurrences` property is not there, for instance.

Please consider republishing to npm. Thanks!

**Comment by ultimate-tester** [comment]
I second this, please consider updating the npm package. This package actually has 39 dependent projects, don't let them down please. I also require the latest version on npm.

Please pay attention to the issues list. I know you're giving this package away for free, but then at least consider your pull requests. The lack of attention from developers is exactly why there's such a mess with packages everywhere! Package A, developed by developer A is good, but not maintained so developer B decides to create a fork of Package A and publishes it as Package B. Then, when developer A finally thinks about pushing changes again to Package A, Package B is hopelessly behind again. Please I beg you to update your package.

At the moment I have 7 vulnerabilities including 1 high vulnerability just because your dependencies are not up-to-date. Why is it that every time there's a nice package I have to create a clone and work on my own version instead of keeping things central and available to everyone... this is the wrong idea of open source.

**Comment by peterbraden** [comment]
I published master to 0.6.0.

But please don't expect any level of support for this module -  as the license states:

"Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,"

I made something, I'm giving it to you for free, you're using it. Demanding any more of my time without pay, or contributions is basically just rude.

"Why is it that every time there's a nice package I have to create a clone and work on my own version instead of keeping things central and available to everyone... this is the wrong idea of open source." <-- this is literally the way open source is meant to work - you have the source, you have the ability to change it to fit your requirements.
